require(shiny) || install.packages("shiny")
require(text2vec) || install.packages("text2vec")
require(tm) || install.packages("tm")
require(tokenizers) || install.packages("tokenizers")
require(wordcloud) || install.packages("wordcloud")
require(slam) || install.packages("slam")
require(maptpx) || install.packages("maptpx")

library(shiny)
library(text2vec)
library(tm)
library(tokenizers)
library(wordcloud)
library(slam)
library(maptpx)