try(require(shiny) || install.packages("shiny"))
try(require(text2vec) || install.packages("text2vec"))
try(require(tm) || install.packages("tm"))
try(require(tokenizers) || install.packages("tokenizers"))
try(require(wordcloud) || install.packages("wordcloud"))
try(require(slam) || install.packages("slam"))
try(require(maptpx) || install.packages("maptpx"))
try(require(igraph) || install.packages("igraph"))

library(shiny)
library(text2vec)
library(tm)
library(tokenizers)
library(wordcloud)
library(slam)
library(maptpx)
library(igraph)